# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: platform-cmp-trail-library
  description: Library of common utilities for the platform compliance trail features
  homepage: https://mytiki.com/platform/compliance
  topics: compliance, audit, library
  private: false
  has_projects: true
  has_discussions: false
  has_issues: true

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: backend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Test

milestones:
  - title: 0.1.4
    description: |
      DRAFT
    state: open
